# Generated by Django 5.2.4 on 2025-08-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillMangement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmodel',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
